//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidationServices.Fluent.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Validators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ValidationServices.Fluent.Resources.Validators", typeof(Validators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Object to validate must implement IComparable interface&quot;.
        /// </summary>
        internal static string ArgumentExceptionMustImplementIComparable {
            get {
                return ResourceManager.GetString("ArgumentExceptionMustImplementIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Lower length constraint must be a zero or a positive number&quot;.
        /// </summary>
        internal static string ArgumentOutOfRangeExceptionInvalidLowerLengthConstraint {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeExceptionInvalidLowerLengthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Upper length constraint must be a zero or a positive number&quot;.
        /// </summary>
        internal static string ArgumentOutOfRangeExceptionInvalidUpperLengthConstraint {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeExceptionInvalidUpperLengthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Max should be larger than min&quot;.
        /// </summary>
        internal static string ArgumentOutOfRangeExceptionMinExceedsMax {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeExceptionMinExceedsMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Property must be empty&quot;.
        /// </summary>
        internal static string EmptyValidatorDefaultFailureMessage {
            get {
                return ResourceManager.GetString("EmptyValidatorDefaultFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Value must be equal to &quot;.
        /// </summary>
        internal static string EqualValidatorDefaultFailureMessage {
            get {
                return ResourceManager.GetString("EqualValidatorDefaultFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This value must be greater than or equal &quot;.
        /// </summary>
        internal static string GreaterThanOrEqualValidatorDefaultFailureMessage {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualValidatorDefaultFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This value must be greater than &quot;.
        /// </summary>
        internal static string GreaterThanValidatorDefaultFailureMessage {
            get {
                return ResourceManager.GetString("GreaterThanValidatorDefaultFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This value must be less than or equal &quot;.
        /// </summary>
        internal static string LessThanOrEqualValidatorDefaultFailureMessage {
            get {
                return ResourceManager.GetString("LessThanOrEqualValidatorDefaultFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This value must be less than &quot;.
        /// </summary>
        internal static string LessThanValidatorDefaultFailureMessage {
            get {
                return ResourceManager.GetString("LessThanValidatorDefaultFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Property must not be empty&quot;.
        /// </summary>
        internal static string NotEmptyValidatorDefaultFailureMessage {
            get {
                return ResourceManager.GetString("NotEmptyValidatorDefaultFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Value must not be equal to &quot;.
        /// </summary>
        internal static string NotEqualValidatorDefaultFailureMessage {
            get {
                return ResourceManager.GetString("NotEqualValidatorDefaultFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Property must not be null&quot;.
        /// </summary>
        internal static string NotNullValidatorDefaultFailureMessage {
            get {
                return ResourceManager.GetString("NotNullValidatorDefaultFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Property must be null&quot;.
        /// </summary>
        internal static string NullValidatorDefaultFailureMessage {
            get {
                return ResourceManager.GetString("NullValidatorDefaultFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Length of a string must satisfy specified constraints&quot;.
        /// </summary>
        internal static string StringLengthValidatorDefaultFailureMessage {
            get {
                return ResourceManager.GetString("StringLengthValidatorDefaultFailureMessage", resourceCulture);
            }
        }
    }
}
